### ISSUE TITLE
Question about Table 1 in the paper

### ISSUE THREAD

**Issue by ycliu93** [google-research/ssl_detection#11]
Hi, 

Thanks for providing this interesting work and releasing the code. I am curious about the implementation details in Table 1 of the main paper. 

(1) Are the results showed in Table 1 produced by using **COCO2017 validation set** (5000 instances)?

(2) In table 1, does the 100% COCO mean that you use **100% supervised COCO2017** data as the labeled set, the external **COCO2017_unlabeled** data as the unlabeled set, and **COCO2017 validation** set as the evaluation set?

Thank you!

**Comment by kihyuks** [comment]
Hello,

(1) yes, you are right. It is evaluated on the COCO validation set.
(2) yes, you are right.

**Comment by ycliu93** [comment]
Thanks, @kihyuks.
