### ISSUE TITLE
Troubles on running code with single GPU (RTX 2070 SUPER) and 16 GB RAM

### ISSUE THREAD

**Issue by happyvictor008** [google-research/ssl_detection#12]
Hello! I was trying to run the code but my process was always being killed by system which said 'out of memory'.
I already set  batch size ==1, so what else can I do to run the code?

**Comment by zizhaozhang** [comment]
Thanks for using the code.

Are you using tf 1.15? I met the OOM issue at that version. Pls follow closely of the environment requirements.

**Comment by happyvictor008** [comment]
Hi,

I’m using tensorflow 1.14-gpu and following all of the instructions.

**Comment by zizhaozhang** [comment]
What GPU type do you use? It requires 16GB mem and we tested on V100

**Comment by happyvictor008** [comment]
Hi,

I’m using rtx2070 super which only has 8GB RAM. I think that’s the problem.

**Comment by happyvictor008** [comment]
Hi,
May I ask is there any way to change the code to reduce the memory use of GPU? I already tried to set  batch size == 1, but it still didn't work. 
Thanks!

**Comment by zizhaozhang** [comment]
No it can not, we already use batch size = 1.

If you are doing experiments on your own datasets and do not care about COCO benchmarks, you can consider reduce the input image size.

**Comment by Chen-Song** [comment]
@zizhaozhang 
Hi, how long does it take to get an experimental result on a single V100? For example, the 1% COCO setting of STAC on Table 1.

**Comment by zizhaozhang** [comment]
@Chen-Song I do not think you can train and get reasonable results using 1 gpu. Since the batch size per GPU is only 1. Too small total batch_size will make network hard to converge.

**Comment by sisrfeng** [comment]
> What GPU type do you use? It requires 16GB mem and we tested on V100

I have two 1080 Ti GPUs, and each has 8G mem left. 
Will it cause any bug?  (I just want to make sure  my environment can run the code, and train the model on more GPUs later.)

Many thx!

To help others:

![image](https://user-images.githubusercontent.com/53520949/100726081-748ce580-33ff-11eb-9cf5-f812513d90a1.png)

**Comment by Chen-Song** [comment]
> @Chen-Song I do not think you can train and get reasonable results using 1 gpu. Since the batch size per GPU is only 1. Too small total batch_size will make network hard to converge.

Thanks, how many GPUs do you use, and how long does it take to get an experimental result in COCO?

**Comment by zizhaozhang** [comment]
@sisrfeng  Each GPU needs to have 16 RAM.  

@Chen-Song We train on 8 V100 and it takes around 8-10 hours.
