### ISSUE TITLE
Where is `prepare_voc_data.py`?

### ISSUE THREAD

**Issue by Retiina** [google-research/ssl_detection#17]
In [`voc_instruction.md`](https://github.com/google-research/ssl_detection/blob/master/prepare_datasets/voc_instruction.md), we need to Generate json files of pascal voc labeled and unlabeled data.
I follow the instruction but can't find `prepare_voc_data.py`, can you help me?
Thanks in advance!

**Comment by MuHeDing** [comment]
Hello，I have the same question？ How do  you solve it?
