### ISSUE TITLE
failed :  wget https://storage.cloud.google.com/gresearch/ssl_detection/STAC_JSON.tar

### ISSUE THREAD

**Issue by sisrfeng** [google-research/ssl_detection#20]
> Need to be authorized

I am in China where The Great Firewall stands.

**Comment by zizhaozhang** [comment]
I uploaded here for you. https://github.com/google-research/ssl_detection/blob/master/prepare_datasets/data/STAC_JSON.tar

**Comment by sisrfeng** [comment]
Thx!!
I tried for several times and finally get 
https://storage.cloud.google.com/gresearch/ssl_detection/STAC_JSON.tar


https://github.com/google-research/ssl_detection/blob/master/prepare_datasets/data/STAC_JSON.tar
is just 61 kb, while 
https://storage.cloud.google.com/gresearch/ssl_detection/STAC_JSON.tar
is 120 Mb

![image](https://user-images.githubusercontent.com/53520949/100686802-08d45980-33ba-11eb-9566-d2c4d5ca993d.png)

Any mistake?

**Comment by zizhaozhang** [comment]
It seems the file is broken. 

Could you install `gsutil` and try `gsutil cp gs://gresearch/ssl_detection/STAC_JSON.tar ./STAC_JSON.tar`

**Comment by sisrfeng** [comment]
![image](https://user-images.githubusercontent.com/53520949/100872036-26014900-34dc-11eb-9ee6-9edc620c95f3.png)
gsutil is not a download tool?

**Comment by zizhaozhang** [comment]
pls see https://cloud.google.com/storage/docs/gsutil

**Comment by ldfinfontainebleau** [comment]
@sisrfeng you can simple use

**Comment by ldfinfontainebleau** [comment]
@sisrfeng you can '''pip3 instal gsutil''' and it will work.

**Comment by sisrfeng** [comment]
pip3 install gsutil
