### ISSUE TITLE
Have you ever tried to generate pseudo-labels online?

### ISSUE THREAD

**Issue by Chen-Song** [google-research/ssl_detection#21]
In STAC, the pseudo-labels are predicted in an offline manner, i.e., after training a network in labeled data and then using it to predict pseudo-labels. It is a multi-stage training manner. However, in FixMatch, also your work, the pseudo-labels are predicted in an online manner, i.e., in a mini-batch, the pseudo-labels are generated. It is a one-stage training manner.

**Comment by kihyuks** [comment]
We haven't tried using online pseudo-label generation approach in the current work but opted for offline generation as it was simpler and faster to implement. It is definitely a viable idea to generate pseudo-labels online as in FixMatch and would be interested to see how it performs.

**Comment by Chen-Song** [comment]
Thanks!
