### ISSUE TITLE
about using my own data

### ISSUE THREAD

**Issue by evangel-jiang** [google-research/ssl_detection#22]
hi
I want to use my own coco-format data on your framework, however, it seems that I need to prepare annotation files (json) for unlabeled data and put them under "$COCODIR/annotations/semi_supervised". Is that true? 
But my own unlabeled data does not have labels. What should I do?
Looking foreword to a practical answer from anyone who can help me!

**Comment by zizhaozhang** [comment]
We follow the coco json format to organize labeled and unlabeled data.
Unlabel data annotation json file is supposed to have boxes field but you can set it as random values. As the code will not use that values during training. Pls read the code `https://github.com/google-research/ssl_detection/blob/master/detection/data.py#L271-L278` to see.

**Comment by evangel-jiang** [comment]
it worked! thank you so much!!!! @zizhaozhang

**Comment by Shuixin-Li** [comment]
Hi @evangel-jiang , I am also encountering this problem. I am really confused about the `boxes` field here, in coco format json, we use `bbox`, do I need to change the `bbox` into `boxes`? I am wondering if you could show an little example of your custom json file. Thank you in advance
