### ISSUE TITLE
VOC Training and Data Scripts missing

### ISSUE THREAD

**Issue by varunnair18** [google-research/ssl_detection#3]
Hi @zizhaozhang , thanks for providing the code to this paper. 

I'm trying to replicate the VOC results but the instructions in [here](https://github.com/google-research/ssl_detection/blob/master/prepare_datasets/voc_instruction.md) were incomplete. When will you be providing the necessary scripts to train the VOC model and is it possible for us to adapt the prepare_coco_data.py easily to do so in the meantime?

Thanks for the help.

**Comment by kihyuks** [comment]
Hi Varun, Sorry for inconvenience. Please find an instruction to download JSON files used for VOC training [here](https://github.com/google-research/ssl_detection/blob/master/DATA.md#download-json-files-for-unlabeled-images-of-coco-data-and-pascal-voc-data) and follow [scripts](https://github.com/google-research/ssl_detection/tree/master/detection/scripts/voc) for experiments. We'll update scripts accordingly soon.

**Comment by varunnair18** [comment]
Great, thank you so much!
