### ISSUE TITLE
Considering label scores in loss function

### ISSUE THREAD

**Issue by ErezBeyond** [google-research/ssl_detection#6]
I can't seem to find where in the code is the **score** of a pseudo box is being taken into account. Specifically, where can we see the effect of zero scored boxes (those that didn't pass the confidence threshold).
To the best of my inquiry, it is missing from the code, though emphasized in the paper.
Thanks!

**Comment by zizhaozhang** [comment]
Pls see this line https://github.com/google-research/ssl_detection/blob/88602f36e322fb0c4d91756d7354abbf839a58fa/detection/data.py#L232

**Comment by ErezBeyond** [comment]
Thanks for the reply!
It seem to me that this eventually **removes** pseudo boxes with lower scores. But this is different than giving them a zero weight, isn't it?
For instance, if the prediction complies with some lower score box, you will penalize for it as a false detection, rather than ignore it (zero weight). Am I missing something here?

**Comment by zizhaozhang** [comment]
Hi

By design in eq (2) of the paper, we use hard threshold so the w(x) is either 1 or 0 (clearly specified in paper). For 0, we directly remove them.

**Comment by ErezBeyond** [comment]
Thank you.
For completeness, I would say that a zero weight is not necessarily equivalent to removing the box. It seems that the formulation in the paper is better expressed in setting these boxes as "don't care" areas.
